version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "npm"
      directory: "/docker/nodejs"
      schedule:
          interval: "daily"
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
          interval: "daily"
