version: "3"

volumes:
    database:
        driver: "local"

networks:
    app:

services:
    database:
        image: "mysql:8.2"
        restart: "always"
        environment:
            MYSQL_ROOT_PASSWORD: "root" # ADJUST
            MYSQL_DATABASE: "servicestatus" # ADJUST
            MYSQL_USER: "servicestatus" # ADJUST
            MYSQL_PASSWORD: "servicestatus" # ADJUST
        volumes:
            - "database:/var/lib/mysql"
        networks:
            - "app"

    app:
        image: "ghcr.io/jensostertag/servicestatus:latest"
        restart: "always"
        volumes:
            - "./secrets:/app/secrets"
        ports:
            - "80:80"
        networks:
            - "app"
